format = '$username$directory$git_branch$git_state$git_status$memory_usage$character'
right_format = '$python$java$rust$cmd_duration'

command_timeout = 1000

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[directory]
read_only = " Ô†Ω"
style = 'bold green'

[git_branch]
symbol = "Ôêò "
style = 'bold blue'

[java]
symbol = "Óâñ "
style = 'bold peach'

[memory_usage]
symbol = "Ô°ö "
threshold = 80
disabled = false
style = "bold teal"

[package]
symbol = "Ô£ñ "

[python]
symbol = "Óàµ "

[rust]
symbol = "ü¶Ä "

[character]
success_symbol = '[Œª](bold peach)'
error_symbol = '[‚ù±](bold red)'

[username]
style_user = "bold maroon"
show_always = true

[time]
disabled = false

[git_status]
untracked = '[‚¨§ ](red)'
modified = '[‚¨§ ](peach)'
staged = '[‚¨§ ](green)'
stashed = 'üì¶ '
format = '$untracked$modified$staged$stashed'
